# Generated by Django 4.2.2 on 2023-06-22 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_otp_profile_delete_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='age',
        ),
    ]
