# Generated by Django 4.2.2 on 2023-06-25 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_is_admin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
