# Generated by Django 4.2.2 on 2023-06-23 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0005_alter_seattype_fare'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='type',
        ),
        migrations.RemoveField(
            model_name='seattype',
            name='flight',
        ),
        migrations.AddField(
            model_name='flight',
            name='fare',
            field=models.IntegerField(default=6000),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Passenger',
        ),
        migrations.DeleteModel(
            name='Seat',
        ),
        migrations.DeleteModel(
            name='SeatType',
        ),
    ]
