# Generated by Django 4.2.2 on 2023-06-23 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0006_remove_seat_type_remove_seattype_flight_flight_fare_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('status', models.IntegerField(choices=[(0, 'Available'), (1, 'Booked')], default=0)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associated_seats', to='flights.flight')),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('gender', models.SmallIntegerField(choices=[(1, 'Male'), (2, 'Female')])),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associated_passengers', to='flights.booking')),
                ('seat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_booking', to='flights.seat')),
            ],
        ),
    ]
