# Generated by Django 4.2.2 on 2023-06-25 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0007_seat_passenger'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.IntegerField(choices=[(0, 'Initiated'), (1, 'Paid')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='passenger',
            name='gender',
            field=models.SmallIntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Others')]),
        ),
    ]
